version: "3.8"

services:
  database:
    container_name: url_shortener_database
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=url_shortener
    ports:
      - 1234:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
